apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-feedback
spec:
  selector:
    matchLabels:
      app: service-feedback
  replicas: 1
  template:
    metadata:
      labels:
        app: service-feedback
    spec:
      containers:
        - name: server
          image: yuliiasupruniuk/service-feedback
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-feedback-svc
spec:
  selector:
    app: service-feedback
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
