apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-user
spec:
  selector:
    matchLabels:
      app: service-user
  replicas: 1
  template:
    metadata:
      labels:
        app: service-user
    spec:
      containers:
        - name: server
          image: yuliiasupruniuk/service-user
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: service-user-svc
spec:
  selector:
    app: service-user
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30002
