
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: users
            - name: POSTGRES_PASSWORD
              value: "timofey"
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          imagePullPolicy: ""
          name: users-db
          ports:
            - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: users-db