server:
  port : 8080

spring:
  application:
    name: FEEDBACK-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8083/eureka/
    instance:
      hostname: localhost